Activity % Complete
The percent of the activity that has been completed.

The calculation is based on the formula for the selected Percent Complete Type. The Percent Complete Type can be Units, Duration, Physical, or Scope.

If the selected activity's percent complete type is Duration, the percent complete is calculated as (Planned Duration minus Remaining Duration) divided by Planned Duration.

If the activity's percent complete type is Units, the percent complete is calculated as (Actual Labor Units plus Actual Nonlabor Units) divided by (Actual Labor Units plus Actual Nonlabor Units plus Remaining Labor Units plus Remaining Nonlabor Units).

If the activity's percent complete type is Physical, either the user records the percent complete manually or the field is set to calculate using steps. To calculate using steps, the Calculate Activity % Complete from activity steps option must be set in Project Preferences.

If the activity's percent complete type is Scope, the percent complete is calculated by Oracle Primavera Cloud and cannot be modified in P6.

In [10]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [11]:
# specify the file path, you might need to adjust this
file_path = "TST00-Update06.xlsx"
# Load the Task data into a DataFrame
task_df = pd.read_excel(file_path, sheet_name='TASK')

In [12]:
def calculate_activity_complete(task_df):
    # Convert only required columns to numeric
    cols_to_convert = ['target_drtn_hr_cnt', 'remain_drtn_hr_cnt',
                       'phys_complete_pct', 'act_work_qty', 'act_equip_qty',
                       'remain_work_qty', 'remain_equip_qty']
    task_df[cols_to_convert] = task_df[cols_to_convert].apply(pd.to_numeric, errors='coerce')

    # Create a new column based on the conditions
    task_df['Activity_%_Complete'] = task_df.apply(lambda row: calculate_percent_complete(row), axis=1)
    return task_df

In [13]:
def calculate_percent_complete(row):
    if row['complete_pct_type'] == 'CP_Drtn':
        return (row['target_drtn_hr_cnt'] - row['remain_drtn_hr_cnt']) / row['target_drtn_hr_cnt'] * 100
    elif row['complete_pct_type'] == 'CP_Phys':
        return row['phys_complete_pct']
    elif row['complete_pct_type'] == 'CP_Units':
        return (row['act_work_qty'] + row['act_equip_qty']) / (
                row['act_work_qty'] + row['act_equip_qty'] + row['remain_work_qty'] + row['remain_equip_qty']) * 100
    else:
        return None

In [14]:
# Assuming task_df is your DataFrame
task_df = calculate_activity_complete(task_df)

In [15]:
task_df

,%F,task_id,proj_id,wbs_id,clndr_id,phys_complete_pct,rev_fdbk_flag,est_wt,lock_plan_flag,auto_compute_act_flag,complete_pct_type,task_type,duration_type,status_code,task_code,task_name,rsrc_id,total_float_hr_cnt,free_float_hr_cnt,remain_drtn_hr_cnt,act_work_qty,remain_work_qty,target_work_qty,target_drtn_hr_cnt,target_equip_qty,act_equip_qty,remain_equip_qty,cstr_date,act_start_date,act_end_date,late_start_date,late_end_date,expect_end_date,early_start_date,early_end_date,restart_date,reend_date,target_start_date,target_end_date,rem_late_start_date,rem_late_end_date,cstr_type,priority_type,suspend_date,resume_date,float_path,float_path_order,guid,tmpl_guid,cstr_date2,cstr_type2,driving_path_flag,act_this_per_work_qty,act_this_per_equip_qty,external_early_start_date,external_late_end_date,create_date,update_date,create_user,update_user,location_id,crt_path_num,Activity_%_Complete
0,%R,316508,1481,85132,993,0,N,1,N,N,CP_Drtn,TT_Task,DT_FixedDUR2,TK_Active,Tst00,Test Activity 00,NaN,7,7,73,0,0,0,100,0,0,0,NaN,2024-06-01 07:00,NaN,2024-06-08 10:00,2024-06-20 13:00,NaN,2024-06-06 13:00,2024-06-19 16:00,2024-06-06 13:00,2024-06-19 16:00,2024-06-01 07:00,2024-06-11 17:00,2024-06-08 10:00,2024-06-20 13:00,NaN,PT_Normal,NaN,NaN,NaN,NaN,P82lMBNJ8kKOInVVkATzaw,6buO9mKJ7UG8R5oPDgJrLQ,NaN,NaN,N,0,0,NaN,NaN,2024-10-25 22:36,2024-10-25 22:36,NotPrmUser,NotPrmUser,NaN,NaN,27.0
1,%R,316509,1481,85132,993,23,N,1,N,N,CP_Phys,TT_Task,DT_FixedDUR2,TK_Active,Tst01,Test Activity 01,NaN,0,0,80,0,0,0,100,0,0,0,NaN,2024-06-01 07:00,NaN,2024-06-06 13:00,2024-06-20 13:00,NaN,2024-06-06 13:00,2024-06-20 13:00,2024-06-06 13:00,2024-06-20 13:00,2024-06-01 07:00,2024-06-11 17:00,2024-06-06 13:00,2024-06-20 13:00,NaN,PT_Normal,NaN,NaN,NaN,NaN,SfkPrPGqQ0GFN+bogKUjzQ,El0B+kM/5ky2YCGDjyhF4Q,NaN,NaN,Y,0,0,NaN,NaN,2024-10-25 22:36,2024-10-25 22:36,NotPrmUser,NotPrmUser,NaN,NaN,23.0
2,%R,316510,1481,85132,993,0,N,1,N,N,CP_Units,TT_Task,DT_FixedDUR2,TK_Active,Tst02,Test Activity 02,1671.0,0,0,80,20,60,100,100,100,20,60,NaN,2024-06-01 07:00,NaN,2024-06-06 13:00,2024-06-20 13:00,NaN,2024-06-06 13:00,2024-06-20 13:00,2024-06-06 13:00,2024-06-20 13:00,2024-06-01 07:00,2024-06-11 17:00,2024-06-06 13:00,2024-06-20 13:00,NaN,PT_Normal,NaN,NaN,NaN,NaN,o8UTsxPHKkClwdIq1Rt3PA,+VrOBvHOmkSTjImOBLv7xA,NaN,NaN,Y,20,20,NaN,NaN,2024-10-25 22:36,2024-10-25 22:36,NotPrmUser,NotPrmUser,NaN,NaN,25.0

In [16]:
# Assuming task_df is your DataFrame
Task_Calculation_df = task_df.loc[:, ['task_id', 'proj_id', 'wbs_id', 'Activity_%_Complete']]

In [17]:
Task_Calculation_df

   task_id  proj_id  wbs_id  Activity_%_Complete
0   316508     1481   85132                 27.0
1   316509     1481   85132                 23.0
2   316510     1481   85132                 25.0

In [18]:
# Assuming Task_Calculation_df is your DataFrame
task_calculation_path = 'Task_Calculation.xlsx'  # you may want to include full path here
with pd.ExcelWriter(task_calculation_path, engine='openpyxl') as writer:
    Task_Calculation_df.to_excel(writer, sheet_name='Task_Calculation', index=False)